### ISSUE TITLE
nobone 1.5.5的renderer.static报错

### ISSUE THREAD

**Issue by hustKiwi** [Baidu-Music-FE/muplayer#86]
升级 `nobone 1.5.5` 后，执行 `no server` 会报如下错误（不影响使用）：
>
Unhandled rejection Error: { [noMatchedHandler: No matched content handler for:/Users/kiwi/muplayer/doc/dist/muplayer_mp3.swf] name: 'noMatchedHandler' }
Trace
  at Function.t.onUnhandledRejection (/Users/kiwi/muplayer/node_modules/nobone/node_modules/nokit/node_modules/nofs/node_modules/yaku/dist/yaku.js:6:822)
  at /Users/kiwi/muplayer/node_modules/nobone/node_modules/nokit/node_modules/nofs/node_modules/yaku/dist/yaku.js:6:2168
  at r (/Users/kiwi/muplayer/node_modules/nobone/node_modules/nokit/node_modules/nofs/node_modules/yaku/dist/yaku.js:6:1171)
  at process._tickCallback (node.js:448:13)

看起来是因为在处理 swf，png 等文件时， `renderer.static` 没有提供默认的 fileRender，导致抛出了异常。但看了下源码，是可以正常进入如下逻辑的：
https://github.com/ysmood/nobone/blob/50044a1889a64b2fd2d238fe62b7fb33d9b1fb78/lib/modules/rendererWidgets.coffee#L407-408

这里是否和 [yaku](https://github.com/ysmood/yaku) 对异常的处理有关呢？
@ysmood

**Comment by hustKiwi** [comment]
https://github.com/ysmood/yaku/issues/2

**Comment by ysmood** [comment]
是的，就是这个 bug，今天晚上打算修正。
